### ISSUE TITLE
Reparenting object with shell fur applied causes brief "flash" of partially unshaded object

### ISSUE THREAD

**Issue by lewiji** [Arnklit/ShellFurGodot#2]
Just wanted to say, this plugin is great and super intuitive to use, thanks for your hard work. The issue below can be worked around by processing the transform to follow the bone manually rather than reparenting, I guess, or possibly by disabling the fur physics for a moment during reparenting, I haven't tried that yet.

**Describe the bug**

When reparenting a node which has the fur effect applied, for a couple of frames part of the "original" object is visible through the effect.

**To Reproduce**

* Create RigidBody with MeshInstance, SphereMesh, apply ShellFur with default settings
* At runtime, remove RigidBody from original parent node, and reparent by adding as child to a different node

**Expected behavior**

The node is reparented without disruption to fur effect

**Screenshots**

https://user-images.githubusercontent.com/233380/115468555-27cd6e00-a22b-11eb-877a-452e0487c86d.mp4

**Environment**
- OS: Linux 5.11
- Graphics card: RTX 2080 SUPER
- Godot version 3.3 rc9
- Plugin version: 0.2.0
- Renderer used: GLES3

**Comment by Arnklit** [comment]
Hmm yeah I think that is just because the fur is moved instantly a distance there and that causes some intense bounce in the physics. Hmm I'll think a bit about the best way to deal with that.

Nice looking game by the way :).

**Comment by lewiji** [comment]
Thanks!

What I just did, since I'm not interested in ever actually seeing the ball mesh, is set a material on the mesh with the `Disable Ambient Light`, `Do Not Receive Shadows` and `Use Shadow To Opacity` flags set, which makes the ball mesh invisible (in my use case anyway). The fur effect then looks great - it bounces back slightly when picked up, and it doesn't appear as though it's clipping.

https://user-images.githubusercontent.com/233380/115576446-690d5e80-a2bb-11eb-9cb8-fc8d34ce939c.mp4

Happy to close this for my use case, though you may have other thoughts on how to solve this, in which case feel free to leave open.

**Comment by Arnklit** [comment]
Yeah I think that is a good solution in your case. Looks good. But yeah I think I should probably have some solution for dealing with the object being moved rapidly for some reason. I could imagine the same issue showing up if people were using it on a character and had to move the character model quickly from one scene to another in a cut scene and the fur would go crazy after the move. I'll add it to my todo list of things to work on for the next update, but close this.
