### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by br3eze** [Arnklit/ShellFurGodot#5]
Hello. It does not work under Godot 3.4.2.
Plan You to add support for 3.4 or it is dead already?

**UPDATE**:
It does work. But if You will create sub-scene it will not render fur,
![Screenshot_20220305_204947](https://user-images.githubusercontent.com/5236855/156886257-e1eec7f0-5382-42ae-aa1a-2b9fdf89f377.png)

Thank You.

**Comment by Arnklit** [comment]
Oh interesting. I'll have a look at this. There are some updates I need to make to in in general. I'll make sure this is fixed and check it against newest Godot soon.

**Comment by br3eze** [comment]
Will You plan to support 4.x branch?

**Comment by Arnklit** [comment]
Yes I plan to make a 4.x version. Was planning on getting started with that when Godot 4.0 hits beta.

**Comment by br3eze** [comment]
Last one thing. Tell me please where can I check this info, when Godot plans releases?
And thanks a lot!

**Comment by Arnklit** [comment]
As far as I know Godot does not have a firm release schedule, they mention goals and targets informally in talks and posts from time to time, but in the end they release when they feel they are ready.

**Comment by Arnklit** [comment]
@br3eze could you try and be a bit more specific on these issues with sub-scenes?  Are you getting any errors logged? Does it work some of the time, but not all the time? I'm testing it now and it works so I can't really troubleshoot it.

You also mention that sometimes the fur doesn't update when you change the base mesh. There is nothing much I can do about this. I assume this is just an issue you for you when you are setting this up in the editor and changing the mesh around? In an actual game you wouldn't be changing out the mesh in runtime. As far as I can tell there is no signal to listen to in Godot about whether a MeshInstance's mesh has been changed, so I can't tell the fur object to update at that point.

**Comment by br3eze** [comment]
Sub-scene. Now, after the last update it works as it should. May be they have changed something. Let's assume this works, at least for a while. I can't repeat it anymore.

Changing a mesh. Try to change radial segments for example. Fur will not update it's shape. May be it's not urgent but that's it.

**Comment by Arnklit** [comment]
Yeah sorry, with regards to the mesh shape, I cannot fix that, if you reload the scene it will be correct, and it would never work to change a shape like that in a running game anyway, so I don't think it's an issue in production, even if it can be annoying during development. I'll add a mention of it to the documentation.

Closing.
