### ISSUE TITLE
 "LOD 1" seems doesn't work at all, eats all the performance at any value.

### ISSUE THREAD

**Issue by br3eze** [Arnklit/ShellFurGodot#7]
If fur is:
- toggled invisible - 76 fps
- LOD == 100% of scene visible - 66 fps. 
- LOD == 20% - 68

Intel HD620, Linux. 

So, what is the point of LOD? Is the scene too small to see LOD's power? But fps even with rtx2060m is below 200 in this scene. Is "cull invisible" works with fur? Or I'm just don't understand something.

(Don't look at fps on this picture, just an example)
![image](https://user-images.githubusercontent.com/5236855/157715872-082d5aa1-a207-413a-aa7a-541fdaaea081.png)

**Comment by Arnklit** [comment]
Will have to investigate this, I'm going over everything in the shaders, so I'll do some tests on this.

**Comment by Arnklit** [comment]
OK, so I've just gone over testing this and it my tests this works as expected. I don't really understand what you mean when you say "LOD 1" doesn't seam to work at all. What do you mean when you say LOD == 100%, LOD == 20%?

Up until the LOD 0 distance you set, the fur will be displayed with all layers. Then between the LOD 0 distance and LOD 1 distance you set the number of layers will decrease down to 25% of the total amount of layers and if you move beyond the LOD1 distance the fur will hide itself by contracting into the object it's on.

I've just been doing tests and the performance acts exactly as expected. Slowest when within the LOD 0 range, then faster and faster the closer it get's to the LOD 1 range and then way faster when beyond the LOD 1 range where all the fur is hidden.

**Comment by br3eze** [comment]
That was my English, sorry. I'll try to rephrase it.
LOD1=100% is when LOD1 draws all fur in a scene. LOD1=20% when only ~20% of fur.

"But fps even with rtx2060m is below 200" this I believe is the engine's baddest side, so we can just pass it: some of it's parts even in simple scenes are sooooo slow.

**Comment by Arnklit** [comment]
OK thanks for the update. Yeah it all looks correct for me in my tests. I'll close this now. I'll be releasing a new version of the addon very soon with a bunch of small fixes, so thanks for using it and giving me feedback.
