### ISSUE TITLE
Gradient

### ISSUE THREAD

**Issue by br3eze** [Arnklit/ShellFurGodot#8]
**Is your feature request related to a problem? Please describe.**
Can't create an adequate looking fur gradient for an animal.

**Describe the solution you'd like**
At least it could be a texture template, but better will be a sliders with some coefficients.

**Comment by Arnklit** [comment]
There is a description on how to go about making your own fur textures and a link to a Material Maker file to get you started in the documentation under tips.

https://github.com/Arnklit/ShellFurGodot#tips

**Comment by br3eze** [comment]
Ow.. I'm sorry for my inattention. Thank You )
